id: P000434
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-16 15:39:45.210316
source_metadata:
  id: bdr:W2DB4593
  title: ནགས་ཀློང་ཁུ་བྱུག་འདུ་གནས
  author: ''
  volumes:
    24eb1932854b495b987f64205fdc6e2e:
      image_group_id: I1PD28034
      title: Volume 1 of nags klong khu byug 'du gnas
      volume_number: 1
      total_pages: 676
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
